### ISSUE TITLE
Fatal error: Class 'sfTimerManager' not found in \myUAITimerAdapter.class.php on line 19

### ISSUE THREAD

**Issue by coldwinds** [quentin389/UserAgentInfo#1]
This external dependency is missing

**Comment by quentin389** [comment]
I'm going to change the code this weekend and make the program require much less work to start up. Cause right now you have to modify `myUAITimerAdapter` and `myUAICacheAdapter` by hand to get it started.
So please, either temporarily edit the files yourself or wait until I change it.

I may remove the timer completely anyway, because that seems more like a development feature, not production one.

**Comment by coldwinds** [comment]
OK, I'll do some hackings on the dependency for the time being.

Thanks.

**Comment by quentin389** [comment]
Btw, what cache will you be using for UserAgentInfo? I'm thinking about adding some cache adapters for popular cache libraries like `phpredis`, `memcache`, and `memcached` but I'm not sure if it even makes sense, because if someone is managing a large site then they will probably have their own class to manage the cache, and would not appreciate a cache adapter that would make a new cache connection for them...

**Comment by quentin389** [comment]
I've released version `1.2` which has the reported problem fixed.

It doesn't use any timers and the whole logic of including cache classes is changed. Hopefully this way of dealing with different people using different caches is correct and I won't have to change it in the future.
